const CATALOG = [
    {
        id: 'el1',
        name: 'СЕРЕБРИСТЫЙ ШАМПУНЬ ДЛЯ ХОЛОДНЫХ ОТТЕНКОВ БЛОНД ESTEL PRIMA BLONDE',
        img: 'img/estel-prima-blond/СЕРЕБРИСТЫЙ ШАМПУНЬ ДЛЯ ХОЛОДНЫХ ОТТЕНКОВ БЛОНД ESTEL PRIMA BLONDE.webp',
        price: 450,
        quantity: 1,
    },
    {
        id: 'el2',
        name: 'СЕРЕБРИСТЫЙ ШАМПУНЬ ДЛЯ ХОЛОДНЫХ ОТТЕНКОВ БЛОНД ESTEL PRIMA BLONDE, 1000 МЛ',
        img: 'img/estel-prima-blond/СЕРЕБРИСТЫЙ ШАМПУНЬ ДЛЯ ХОЛОДНЫХ ОТТЕНКОВ БЛОНД ESTEL PRIMA BLONDE, 1000 МЛ.webp',
        price: 900,
        quantity: 1,
    },
    {
        id: 'el3',
        name: 'СЕРЕБРИСТЫЙ БАЛЬЗАМ ДЛЯ ХОЛОДНЫХ ОТТЕНКОВ БЛОНД ESTEL PRIMA BLONDE',
        img: 'img/estel-prima-blond/СЕРЕБРИСТЫЙ БАЛЬЗАМ ДЛЯ ХОЛОДНЫХ ОТТЕНКОВ БЛОНД ESTEL PRIMA BLONDE.webp',
        price: 450,
        quantity: 1,
    },
    {
        id: 'el4',
        name: 'СЕРЕБРИСТАЯ МАСКА ДЛЯ ХОЛОДНЫХ ОТТЕНКОВ БЛОНД ESTEL PRIMA BLONDE',
        img: 'img/estel-prima-blond/СЕРЕБРИСТАЯ МАСКА ДЛЯ ХОЛОДНЫХ ОТТЕНКОВ БЛОНД ESTEL PRIMA BLONDE.webp',
        price: 650,
        quantity: 1,
    },
    {
        id: 'el5',
        name: 'БЛЕСК-ШАМПУНЬ ДЛЯ СВЕТЛЫХ ВОЛОС ESTEL PRIMA BLONDE',
        img: 'img/estel-prima-blond/БЛЕСК-ШАМПУНЬ ДЛЯ СВЕТЛЫХ ВОЛОС ESTEL PRIMA BLONDE.webp',
        price: 450,
        quantity: 1,
    },
    {
        id: 'el6',
        name: 'БЛЕСК-ШАМПУНЬ ДЛЯ СВЕТЛЫХ ВОЛОС ESTEL PRIMA BLONDE, 1000 МЛ',
        img: 'img/estel-prima-blond/БЛЕСК-ШАМПУНЬ ДЛЯ СВЕТЛЫХ ВОЛОС ESTEL PRIMA BLONDE, 1000 МЛ.webp',
        price: 900,
        quantity: 1,
    },
    {
        id: 'el7',
        name: 'БЛЕСК-БАЛЬЗАМ ДЛЯ СВЕТЛЫХ ВОЛОС ESTEL PRIMA BLONDE',
        img: 'img/estel-prima-blond/БЛЕСК-БАЛЬЗАМ ДЛЯ СВЕТЛЫХ ВОЛОС ESTEL PRIMA BLONDE.webp',
        price: 450,
        quantity: 1,
    },
    {
        id: 'el8',
        name: 'КОМФОРТ-МАСКА ДЛЯ СВЕТЛЫХ ВОЛОС ESTEL PRIMA BLONDE',
        img: 'img/estel-prima-blond/КОМФОРТ-МАСКА ДЛЯ СВЕТЛЫХ ВОЛОС ESTEL PRIMA BLONDE.webp',
        price: 650,
        quantity: 1,
    },
    {
        id: 'el9',
        name: 'ДВУХФАЗНЫЙ СПРЕЙ ДЛЯ СВЕТЛЫХ ВОЛОС ESTEL PRIMA BLONDE',
        img: 'img/estel-prima-blond/ДВУХФАЗНЫЙ СПРЕЙ ДЛЯ СВЕТЛЫХ ВОЛОС ESTEL PRIMA BLONDE.webp',
        price: 450,
        quantity: 1,
    },
    {
        id: 'el10',
        name: 'МАСЛО-УХОД ДЛЯ СВЕТЛЫХ ВОЛОС ESTEL PRIMA BLONDE',
        img: 'img/estel-prima-blond/МАСЛО-УХОД ДЛЯ СВЕТЛЫХ ВОЛОС ESTEL PRIMA BLONDE.webp',
        price: 650,
        quantity: 1,
    },
    {
        id: 'el11',
        name: 'СЕРЕБРИСТЫЙ БАЛЬЗАМ ДЛЯ ХОЛОДНЫХ ОТТЕНКОВ БЛОНД ESTEL PRIMA BLONDE, 1000 МЛ',
        img: 'img/estel-prima-blond/СЕРЕБРИСТЫЙ БАЛЬЗАМ ДЛЯ ХОЛОДНЫХ ОТТЕНКОВ БЛОНД ESTEL PRIMA BLONDE, 1000 МЛ.webp',
        price: 1050,
        quantity: 1,
    }
];